Before starting the project let's connect to the github repository

Now that the account is connected, let's start by importing the right libraries and gathering the data.
The first data is about traffic accident, available as a json at this address

In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
url = 'https://esploradati.istat.it/SDMXWS/rest/data/41_983'
header = {'Accept': 'application/vnd.sdmx.data+csv;version=1.0.0'}
params = {
    'startPeriod' : 2020
}

In [ ]:
data = requests.get(url, headers=header, params=params, stream=True)
data.raise_for_status()

with open("database_car_accident.csv", 'w') as file:
    file.write(data.text)

Now that the first part of the data has been downloaded, we can proceed with the second part.
After downloading the file about italian cities [`https://situas.istat.it/web/#/territorio/body?id=74&dateFrom=2020-12-31], let's analyze the data.

In [2]:
car_accident = pd.read_csv('data/database_car_accident.csv')
print(car_accident.info())

<class 'pandas.DataFrame'>
RangeIndex: 113856 entries, 0 to 113855
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          113856 non-null  str
 1   FREQ              113856 non-null  str
 2   REF_AREA          113856 non-null  int64
 3   DATA_TYPE         113856 non-null  str
 4   RESULT            113856 non-null  str
 5   TIME_PERIOD       113856 non-null  int64
 6   OBS_VALUE         113856 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(3), str(4)
memory usage: 13.9 MB
None

With that script we can observe that all data contained in the last 9 columns return as null, meaning they are empty. Now let's see what data the other columns have and if they are all unique

In [3]:
for name in list(car_accident)[:7]:
    print(f'For the column {name} we have these unique values: ')
    print(car_accident[name].unique())

For the column DATAFLOW we have these unique values:
<StringArray>
['IT1:41_983(1.0)']
Length: 1, dtype: str
For the column FREQ we have these unique values:
<StringArray>
['A']
Length: 1, dtype: str
For the column REF_AREA we have these unique values:
[  1001   1002   1003 ... 111105 111106 111107]
For the column DATA_TYPE we have these unique values:
<StringArray>
['KILLINJ', 'ROADACC']
Length: 2, dtype: str
For the column RESULT we have these unique values:
<StringArray>
['F', 'M', '9']
Length: 3, dtype: str
For the column TIME_PERIOD we have these unique values:
[2020 2021 2022 2023 2024]
For the column OBS_VALUE we have these unique values:
[    4     2     5     6     0     1     3    14     9    10     8     7
    25    46    31    36    24    18    30    23    27    20    39    32
    50    54    47    40    34    11    38    43    22    29    21    33
    12    17    13    15    16    19    58    97    80    86   102    37
    70    55    62    71    45    28    35    49    67    66    73    90
    60    65    68    84   115    83    41    26    42   112   203   206
   190   205    81   138   136   130    51    76    56    61    72    79
    57    48    53    44   199   180   139   250   152   127   106   175
    99   168   147   111   123   120    95    59    69   105    75   103
   116    77    82    52   142   218   236   212   239   164   157   166
    93   140   154   171   174   101   107   122  2969  3918  4163  4131
  4288  2088  2793  2935  2918  2968   110   181   200   234    96   135
   146   167   100    74   338   493   508   546   552   256   383   404
   408   413    78    63    85   244   275   296   165   208   215   220
    88    94    64   265   334   356   297   397   194   277   302   405
   456   498   532   270   329   345   385   420   109   113   131    91
   108   132   121    89   133   163   151    87   148    98   258   282
   290   185   209   229   316   370   378   443   274   304   320   358
   104   129   124   153   178   155   128   172   281   355   470   448
   492   238   384   375   409   173   198   150  3327  4239  4662  4339
  4594  2840  3584  3910  3669  3872   118   196   191   159   156   125
    92   537   555   522   598   446   415   524   119   331   520   481
   528   252   393   414   237   359   350   292   306   295   114   162
   117   286   441   379   395   482   307   313   373   149   326   509
   322   366   357   406   243   294   453   461   225   353   348   169
   137   126   143   245   300   344   382   376   193   240   280   288
  6035  9286  9865  9709  9585  4856  7465  7783  7812  7743   195   183
   293   303   284   221   207   242   176   177   342   228   253   323
   771  1072  1159  1098  1078   620   851   927   891   893   134   182
   696   953  1011  1085  1055   543   723   841   860   474   450   399
   335   365   339   318   188   202   145   312   440   466   337   354
   310   232   315   267   548   681   770   793   846   454   564   659
   660   170   158   141   467   261   341   349  1101  1409  1501  1418
  1515   868  1129  1252  1170  1230   161   539   573   540   432   452
   144   386   411   325   279   230   227   210   219   217   160   628
   749   898   847   476   590   700   662   669   961  1326  1369  1278
  1302   754  1019  1028   213   257   247   204   392   426   495   351
   332   743   987  1032   958   994   624   827   867   790   837   581
   652   688   721   390   477   523   557   667   839   999   929   948
   671   783   755   780   678   926   957  1058  1077   734   761   802
   276  1156  1260  1313  1280   695   934   992  1000  1014   186  1652
  2412  2700  2731  2439  1318  1919  2120  2158  1946   278   381   264
   324   179   437   566   717   469   514   561   603   189   364   226
   308   702   877  1037   967  1043   663   799   760   813   422   455
   568   328   361   407   428   439   500   596   685   609   633   472
   529   497   287   184   233   251   263   289   547   579   567   391
   436   434   584   591   599   556   445   451   224   266   214   262
   197   211   192   231   248   255   333   347   309   368   449   592
   513   268   246   371   485   519   389   402   269   473   398   403
   504   496   489   291   254   241  1766  2403  3023  3018  2697  1493
  2028  2627  2580  2291   330   235   283   767  1070  1110  1133  1227
   612   863   900   923   997   419   715   670   716   559   336   457
   418   273   362   272   285   222   394   533   505   305   216   417
   542   607   586   657   425   458   502   396   479   503   545   374
   430   388   447   187 10452 13862 16618 16023 17196  8229 11129 13181
 12817 13924   412   401   435   483   317   223   431   554   707   649
   672   260  2266  2771  3051  3067  3262  1796  2163  2337  2379  2544
   201   739   857   764   736   578   352   423   459   534   327   752
   740   737   873   380   444   515  1605  2238  2528  1092  1446  1506
  1563  1777   711   869   905  1076  1339   611   617   724   593   463
   372   518  1729  2051  2346  2503  2576  1358  1607  1795  1886  1987
   838  1049   966   988  1042   738   768   501  1288  1576  1905  1902
  2043  1162  1376  1459   465   583   544   299   665   701   689   490
   530   574   632   427  1026  1062  1004   844   876   854   683   936
   941   897   962   759   775   833   658   694   661   692   575   271
   480]

for the colums that have data inside let's download the dataflow from this endpoint: https://esploradati.istat.it/SDMXWS/rest/dataflow/IT1/41_983. 
With this data we can have an isnight on what each column and value actually means

-DATAFLOW -> Refers to the dataset id, should be safe to ignore that data 

-FREQ -> Refers to the frequency of the data (annually) 

-REF_AREA -> connected to the Codice Comune (alfanumerico) found in the second database

-DATA_TYPE -> KILLINJ stands for deceased and injured, ROADACC only for injured

-RESULT -> M is for deceased, F is for Injured and 9 is for total

In [ ]:
#RIGA 200
<structure:Code id="M">
  <common:Name xml:lang="en">killed</common:Name>
  <common:Name xml:lang="it">morto</common:Name>
</structure:Code>
<structure:Code id="F">
  <common:Name xml:lang="en">injured</common:Name>
  <common:Name xml:lang="it">ferito</common:Name>
</structure:Code>
<structure:Code id="9">
  <common:Name xml:lang="en">total</common:Name>
  <common:Name xml:lang="it">totale</common:Name>
</structure:Code>

#Riga 187.766
<structure:Code id="KILLINJ">
  <common:Name xml:lang="it">morti e feriti</common:Name>
</structure:Code>
<structure:Code id="ROADACC">
  <common:Name xml:lang="it">incidenti stradali con lesioni alle persone</common:Name>
</structure:Code>

Now let's do the same for the other database

In [102]:
#in this case I had to change the default separator to get an accurate reading
cities_2020 = pd.read_csv('data/comuni_italiani_2020.csv', sep=';')
print(cities_2020.info())

<class 'pandas.DataFrame'>
RangeIndex: 7903 entries, 0 to 7902
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  7903 non-null   int64
 1   Codice Regione                  7903 non-null   int64
 2   Codice Provincia (Storico)      7903 non-null   int64
 3   Codice Provincia/Uts            7903 non-null   int64
 4   Codice Comune (alfanumerico)    7903 non-null   int64
 5   Codice Comune (numerico)        7903 non-null   int64
 6   Comune                          7902 non-null   str
 7   Comune (dizione straniera)      124 non-null    str
 8   Sigla automobilistica           7811 non-null   str
 9   Capoluogo di Provincia/Uts      7903 non-null   int64
 10  Capoluogo di Regione            7903 non-null   int64
 11  Popolazione legale              7903 non-null   int64
 12  Anno Censimento                 7903 non-null   int64
 13  Superficie (Kmq)                7903 non-null   str
 14  Anno (Superficie)               7903 non-null   int64
 15  Popolazione residente           7903 non-null   int64
 16  Anno (Popolazione residente)    7903 non-null   int64
dtypes: int64(13), str(4)
memory usage: 1.0 MB
None

This database is different, it contains null values in 3 columns (Comune, Comune (dizione straniera) and Sigla automobilistica). 
we can safely ignore the Comune (dizione straniera) since for this analysis our interest is on the local names, while for the others two it's worth investigating a little bit

In [103]:
comune_missing_value = cities_2020[cities_2020['Comune'].isnull()]
comune_missing_value

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
164,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7998,2011,"24,6422",2020,7849,2020

In [ ]:
sigla_missing_value = cities_2020[cities_2020['Sigla automobilistica'].isnull()]
sigla_missing_value

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
5066,4,15,63,263,63001,63001,Acerra,NaN,NaN,0,0,56465,2011,"54,7117",2020,58334,2020
5067,4,15,63,263,63002,63002,Afragola,NaN,NaN,0,0,63820,2011,"17,9106",2020,61861,2020
5068,4,15,63,263,63003,63003,Agerola,NaN,NaN,0,0,7373,2011,"19,8316",2020,7640,2020
5069,4,15,63,263,63004,63004,Anacapri,NaN,NaN,0,0,6546,2011,"6,4666",2020,6940,2020
5070,4,15,63,263,63005,63005,Arzano,NaN,NaN,0,0,34933,2011,"4,7310",2020,32750,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5153,4,15,63,263,63088,63088,Visciano,NaN,NaN,0,0,4550,2011,"10,9036",2020,4226,2020
5154,4,15,63,263,63089,63089,Volla,NaN,NaN,0,0,22989,2011,"6,2063",2020,24905,2020
5155,4,15,63,263,63090,63090,Santa Maria la Carità,NaN,NaN,0,0,11726,2011,"3,9788",2020,11685,2020
5156,4,15,63,263,63091,63091,Trecase,NaN,NaN,0,0,9118,2011,"6,2131",2020,8643,2020
5157,4,15,63,263,63092,63092,Massa di Somma,NaN,NaN,0,0,5587,2011,"3,0421",2020,5019,2020

The missing value in the comune column is from the UTS 201, which corresponds to the city of Torino.
For the missing values in the Sigla automobilistica column, it seems they all are from the city of Napoli, so the NaN value is replaved with NA

In [6]:
comune_missing_value['Comune'] = 'Torino'
sigla_missing_value['Sigla automobilistica'] = "NA"

In [ ]:
for name in list(cities_2020):
    print(f'For the column {name} we have these unique values: ')
    print(cities_2020[name].unique())

For the column Codice Ripartizione geografica we have these unique values:
[1 2 3 4 5]
For the column Codice Regione we have these unique values:
[ 1  2  7  3  4  5  6  8 11  9 10 12 15 13 14 16 17 18 19 20]
For the column Codice Provincia (Storico) we have these unique values:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 108 109 110 111]
For the column Codice Provincia/Uts we have these unique values:
[201   2   3   4   5   6   7   8   9 210  11  12  13  14 215  16  17  18
  19  20  21  22  23  24  25  26 227  28  29  30  31  32  33  34  35  36
 237  38  39  40  41  42  43  44  45  46  47 248  49  50  51  52  53  54
  55  56  57 258  59  60  61  62 263  64  65  66  67  68  69  70  71 272
  73  74  75  76  77  78  79 280  81 282 283  84  85  86 287  88  89  90
  91 292  93  94  95  96  97  98  99 100 101 102 103 108 109 110 111]
For the column Codice Comune (alfanumerico) we have these unique values:
[  1001   1002   1003 ... 111105 111106 111107]
For the column Codice Comune (numerico) we have these unique values:
[  1001   1002   1003 ... 111105 111106 111107]
For the column Comune we have these unique values:
<StringArray>
[          'Agliè',         'Airasca',    'Ala di Stura', 'Albiano d'Ivrea',
          'Almese',         'Alpette',       'Alpignano',        'Andezeno',
         'Andrate',        'Angrogna',
 ...
  'Villamassargia',  'Villanova Tulo',  'Villanovaforru', 'Villanovafranca',
   'Villaperuccio',      'Villaputzu',      'Villasalto',     'Villasimius',
        'Villasor',   'Villaspeciosa']
Length: 7897, dtype: str
For the column Comune (dizione straniera) we have these unique values:
<StringArray>
[                                   nan,
                               'Aldein',
                              'Andrian',
                               'Altrei',
              'Eppan an der Weinstraße',
                              'Hafling',
                                'Abtei',
                              'Barbian',
                                'Bozen',
                                'Prags',
 ...
                               'Wengen',
 'Unsere Liebe Frau im Walde-St. Felix',
                              'Sèn Jan',
                             'Doberdob',
                            'Števerjan',
                     'Sovodnje ob Soči',
                      'Devin Nabrežina',
                           'Repentabor',
                               'Dolina',
                               'Zgonik']
Length: 125, dtype: str
For the column Sigla automobilistica we have these unique values:
<StringArray>
['TO', 'VC', 'NO', 'CN', 'AT', 'AL', 'AO', 'IM', 'SV', 'GE',
 ...
 'LO', 'RN', 'PO', 'KR', 'VV', 'VB', 'MB', 'FM', 'BT', 'SU']
Length: 107, dtype: str
For the column Capoluogo di Provincia/Uts we have these unique values:
[0 1]
For the column Capoluogo di Regione we have these unique values:
[0 1]
For the column Popolazione legale we have these unique values:
[2644 3819  462 ... 3420 6857 2407]
For the column Anno Censimento we have these unique values:
[2011]
For the column Superficie (Kmq) we have these unique values:
<StringArray>
[ '13,1462',  '15,7393',  '46,3315',  '11,7314',  '17,8756',   '5,6261',
  '11,9193',   '7,4860',   '9,3085',  '38,8782',
 ...
  '91,3876',  '40,4494',  '10,9328',  '27,5900',  '36,4283', '181,3074',
 '130,3596',  '57,9708',  '86,7935',  '27,1937']
Length: 7857, dtype: str
For the column Anno (Superficie) we have these unique values:
[2020]
For the column Popolazione residente we have these unique values:
[2545 3633  459 ... 4497  999 6636]
For the column Anno (Popolazione residente) we have these unique values:
[2020]

The Codice Ripartizione geografica is a range of number (from 1 to 5) used to divide italy in:
1 - North-west (Piemonte, Valle d'Aosta, Liguria, Lombardia)
2 - North-est (Trentino-Alto Adige, Veneto, Friuli-Venezia Giulia, Emilia-Romagna)
3 - Center (Toscana, Umbria, Marche, Lazio)
4 - South (Abruzzo, Molise, Campania, Puglia, Basilicata, Calabria)
5 - Islands (Sicilia, Sardegna)

The Codice Regione is an identification number (that goes from 1 to 21) set by the Agenzia delle Entrate
01 - Abruzzo
02 - Basilicata
03 - Bolzano (P.A.)
04 - Calabria
05 - Campania
06 - Emilia-Romagna
07 - Friuli-Venezia Giulia
08 - Lazio
09 - Liguria
10 - Lombardia
11 - Marche
12 - Molise
13 - Piemonte
14 - Puglia
15 - Sardegna
16 - Sicilia
17 - Toscana
18 - Trento (P.A.)
19 - Umbria
20 - Valle d'Aosta
21 - Veneto

Codice Provincia (Storico) can be ignored, it's used by ISTAT to keep tracks of cities in historical data

Codice Provincia/Uts is the one in use, and there are currently 107

In [133]:
cities_2020['Codice Provincia/Uts'].value_counts()
cities_2020.info()

<class 'pandas.DataFrame'>
RangeIndex: 7903 entries, 0 to 7902
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  7903 non-null   int64
 1   Codice Regione                  7903 non-null   int64
 2   Codice Provincia (Storico)      7903 non-null   int64
 3   Codice Provincia/Uts            7903 non-null   int64
 4   Codice Comune (alfanumerico)    7903 non-null   int64
 5   Codice Comune (numerico)        7903 non-null   int64
 6   Comune                          7902 non-null   str
 7   Comune (dizione straniera)      124 non-null    str
 8   Sigla automobilistica           7811 non-null   str
 9   Capoluogo di Provincia/Uts      7903 non-null   int64
 10  Capoluogo di Regione            7903 non-null   int64
 11  Popolazione legale              7903 non-null   int64
 12  Anno Censimento                 7903 non-null   int64
 13  Superficie (Kmq)                7903 non-null   str
 14  Anno (Superficie)               7903 non-null   int64
 15  Popolazione residente           7903 non-null   int64
 16  Anno (Popolazione residente)    7903 non-null   int64
dtypes: int64(13), str(4)
memory usage: 1.0 MB

For the Codice Comune (alfanumerico) and Codice Comune (numerico) both of them are identical

Now that we have a clear insight of what each column actually does, let's remove some columns and download the rest of the data, since the file for 'comuni_italiani.csv' only has entries for 2020. This is because we need for each year the updated number of legal residents to make a correct analysis.

In [181]:
polished_car_accident = car_accident[['REF_AREA', 'DATA_TYPE', 'RESULT', 'TIME_PERIOD', 'OBS_VALUE']]
polished_cities_2020 = cities_2020.iloc[:, [1,3,5,6,11,14,13]]

#Let's do the same for the other data, from 2021 to 2022
cities_2021 = pd.read_csv('data/comuni_italiani_2021.csv', sep=';')
cities_2022 = pd.read_csv('data/comuni_italiani_2022.csv', sep=';')
cities_2023 = pd.read_csv('data/comuni_italiani_2023.csv', sep=';')
cities_2024 = pd.read_csv('data/comuni_italiani_2024.csv', sep=';')

polished_cities_2021 = cities_2021.iloc[:, [5,14,11]]
polished_cities_2022 = cities_2022.iloc[:, [5,14,11]]
polished_cities_2023 = cities_2023.iloc[:, [5,14,11]]
polished_cities_2024 = cities_2024.iloc[:, [5,14,11]]


concat_cities = [polished_cities_2020, polished_cities_2021, polished_cities_2022, polished_cities_2023, polished_cities_2024]
polished_cities_complete = pd.concat(concat_cities).iloc[:,[2,5,4]].rename(columns={'Codice Comune (numerico)':'Codice Comune', 'Anno (Superficie)': 'Anno'})

Now that we have isolated the data we need for our analysis let's merge it togheter in a single csv file and save it

In [183]:
polished_car_accident.head(1)

   REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
0      1001   KILLINJ      F         2020          4

In [189]:
complete_dataset = polished_car_accident.merge(
    polished_cities_complete,
    left_on=['REF_AREA', 'TIME_PERIOD'],
    right_on=['Codice Comune', 'Anno']
)
complete_dataset.head(15)

,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,Codice Comune,Anno,Popolazione legale
0,1001,KILLINJ,F,2020,4,1001,2020,2644
1,1001,KILLINJ,F,2021,2,1001,2021,2562
2,1001,KILLINJ,F,2022,5,1001,2022,2562
3,1001,KILLINJ,F,2023,6,1001,2023,2562
4,1001,KILLINJ,F,2024,5,1001,2024,2562
5,1001,KILLINJ,M,2020,0,1001,2020,2644
6,1001,KILLINJ,M,2021,0,1001,2021,2562
7,1001,KILLINJ,M,2022,0,1001,2022,2562
8,1001,KILLINJ,M,2023,1,1001,2023,2562
9,1001,KILLINJ,M,2024,0,1001,2024,2562
10,1001,ROADACC,9,2020,4,1001,2020,2644
11,1001,ROADACC,9,2021,2,1001,2021,2562
12,1001,ROADACC,9,2022,3,1001,2022,2562
13,1001,ROADACC,9,2023,3,1001,2023,2562
14,1001,ROADACC,9,2024,2,1001,2024,2562

Now that the cleanup is completed, let's proceed with saving the whole database in a new file

In [190]:
complete_dataset.to_csv('data/complete_dataset.csv')